In [1]:
def fibonacci():
    '''Infinite fibonacci series'''
    x, y = 0, 1
    while True:
        yield x
        x, y = y, x + y

In [9]:
from __future__ import print_function
g = fibonacci()
for _ in range(34):
    print('{:,}'.format(next(g)), end=' ')

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1,597 2,584 4,181 6,765 10,946 17,711 28,657 46,368 75,025 121,393 196,418 317,811 514,229 832,040 1,346,269 2,178,309 3,524,578

In [4]:
import itertools

In [7]:
for fib in itertools.islice(fibonacci(), 50):
    print('{:,}'.format(fib), end='; ')

0; 1; 1; 2; 3; 5; 8; 13; 21; 34; 55; 89; 144; 233; 377; 610; 987; 1,597; 2,584; 4,181; 6,765; 10,946; 17,711; 28,657; 46,368; 75,025; 121,393; 196,418; 317,811; 514,229; 832,040; 1,346,269; 2,178,309; 3,524,578; 5,702,887; 9,227,465; 14,930,352; 24,157,817; 39,088,169; 63,245,986; 102,334,155; 165,580,141; 267,914,296; 433,494,437; 701,408,733; 1,134,903,170; 1,836,311,903; 2,971,215,073; 4,807,526,976; 7,778,742,049;

In [8]:
import numpy

In [9]:
import pandas

In [10]:
import numpy as np

In [11]:
import pandas as pd

In [12]:
np.random.seed(42)

In [41]:
x = np.random.rand(10_000_000)

In [42]:
%%timeit
y = np.empty(len(x))
for i in range(len(x)):
    y[i] = 2 * x[i] + 1

5.21 s ± 291 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [43]:
%%timeit
y = 2 * x + 5

28.3 ms ± 421 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [True, True, False], 'C': np.random.randn(3)}, index=['a', 'b', 'c'])

In [9]:
df

   A      B         C
a  1   True  0.496714
b  2   True -0.138264
c  3  False  0.647689

In [18]:
df.loc['b':'c', 'B':'C']

       B         C
b   True -0.138264
c  False  0.647689

In [23]:
df.iloc[0:2, 0:1]

   A
a  1
b  2

In [24]:
df2 = pd.DataFrame(np.random.uniform(0, 10, size=(3,3)))

In [25]:
df2

          0         1         2
0  1.560186  1.559945  0.580836
1  8.661761  6.011150  7.080726
2  0.205845  9.699099  8.324426

In [26]:
df2 + 1

          0          1         2
0  2.560186   2.559945  1.580836
1  9.661761   7.011150  8.080726
2  1.205845  10.699099  9.324426

In [27]:
df2 ** 2

           0          1          2
0   2.434182   2.433429   0.337371
1  75.026112  36.133926  50.136678
2   0.042372  94.072512  69.296075

In [28]:
np.log(df2)

          0         1         2
0  0.444805  0.444651 -0.543287
1  2.158918  1.793616  1.957376
2 -1.580632  2.272033  2.119194

In [29]:
import toolz

In [30]:
help(toolz)

Help on package toolz:

NAME
    toolz

PACKAGE CONTENTS
    compatibility
    curried (package)
    dicttoolz
    functoolz
    itertoolz
    recipes
    sandbox (package)
    utils

FUNCTIONS
    reduce(...)
        reduce(function, sequence[, initial]) -> value

        Apply a function of two arguments cumulatively to the items of a sequence,
        from left to right, so as to reduce the sequence to a single value.
        For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
        ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
        of the sequence in the calculation, and serves as a default when the
        sequence is empty.

    sorted(...)
        sorted(iterable, key=None, reverse=False) --> new sorted list

VERSION
    0.7.4

FILE
    /Users/pbrown/.virtualenvs/notebooks/lib/python3.4/site-packages/toolz/__init__.py

In [31]:
help(toolz.itertoolz)

Help on module toolz.itertoolz in toolz:

NAME
    toolz.itertoolz

FUNCTIONS
    accumulate(binop, seq, initial='__no__default__')
        Repeatedly apply binary function to a sequence, accumulating results

        >>> from operator import add, mul
        >>> list(accumulate(add, [1, 2, 3, 4, 5]))
        [1, 3, 6, 10, 15]
        >>> list(accumulate(mul, [1, 2, 3, 4, 5]))
        [1, 2, 6, 24, 120]

        Accumulate is similar to ``reduce`` and is good for making functions like
        cumulative sum:

        >>> from functools import partial, reduce
        >>> sum    = partial(reduce, add)
        >>> cumsum = partial(accumulate, add)

        Accumulate also takes an optional argument that will be used as the first
        value. This is similar to reduce.

        >>> list(accumulate(add, [1, 2, 3], -1))
        [-1, 0, 2, 5]
        >>> list(accumulate(add, [], 1))
        [1]

        See Also:
            itertools.accumulate :  In standard itertools for Python 3.2+

    concat(seqs)
        Concatenate zero or more iterables, any of which may be infinite.

        An infinite sequence will prevent the rest of the arguments from
        being included.

        We use chain.from_iterable rather than chain(*seqs) so that seqs
        can be a generator.

        >>> list(concat([[], [1], [2, 3]]))
        [1, 2, 3]

        See also:
            itertools.chain.from_iterable  equivalent

    concatv(*seqs)
        Variadic version of concat

        >>> list(concatv([], ["a"], ["b", "c"]))
        ['a', 'b', 'c']

        See also:
            itertools.chain

    cons(el, seq)
        Add el to beginning of (possibly infinite) sequence seq.

        >>> list(cons(1, [2, 3]))
        [1, 2, 3]

    count(seq)
        Count the number of items in seq

        Like the builtin ``len`` but works on lazy sequencies.

        Not to be confused with ``itertools.count``

        See also:
            len

    diff(*seqs, **kwargs)
        Return those items that differ between sequences

        >>> list(diff([1, 2, 3], [1, 2, 10, 100]))
        [(3, 10)]

        Shorter sequences may be padded with a ``default`` value:

        >>> list(diff([1, 2, 3], [1, 2, 10, 100], default=None))
        [(3, 10), (None, 100)]

        A ``key`` function may also be applied to each item to use during
        comparisons:

        >>> list(diff(['apples', 'bananas'], ['Apples', 'Oranges'], key=str.lower))
        [('bananas', 'Oranges')]

    drop(n, seq)
        The sequence following the first n elements

        >>> list(drop(2, [10, 20, 30, 40, 50]))
        [30, 40, 50]

        See Also:
            take
            tail

    first(seq)
        The first element in a sequence

        >>> first('ABC')
        'A'

    frequencies(seq)
        Find number of occurrences of each value in seq

        >>> frequencies(['cat', 'cat', 'ox', 'pig', 'pig', 'cat'])  #doctest: +SKIP
        {'cat': 3, 'ox': 1, 'pig': 2}

        See Also:
            countby
            groupby

    get(ind, seq, default='__no__default__')
        Get element in a sequence or dict

        Provides standard indexing

        >>> get(1, 'ABC')       # Same as 'ABC'[1]
        'B'

        Pass a list to get multiple values

        >>> get([1, 2], 'ABC')  # ('ABC'[1], 'ABC'[2])
        ('B', 'C')

        Works on any value that supports indexing/getitem
        For example here we see that it works with dictionaries

        >>> phonebook = {'Alice':  '555-1234',
        ...              'Bob':    '555-5678',
        ...              'Charlie':'555-9999'}
        >>> get('Alice', phonebook)
        '555-1234'

        >>> get(['Alice', 'Bob'], phonebook)
        ('555-1234', '555-5678')

        Provide a default for missing values

        >>> get(['Alice', 'Dennis'], phonebook, None)
        ('555-1234', None)

        See Also:
            pluck

    groupby(key, seq)
        Group a collection by a key function

        >>> names = ['Alice', 'Bob', 'Charlie', 'Dan', 'Edith', 'Frank']
        >>> groupby(len, names)  # doctest: +SKIP
        {3: ['Bob', 'Dan'], 5: ['Alice', 'Edith', 'Frank'], 7: ['Charlie']}

        >>> iseven = lambda x: x % 2 == 0
        >>> groupby(iseven, [1, 2, 3, 4, 5, 6, 7, 8])  # doctest: +SKIP
        {False: [1, 3, 5, 7], True: [2, 4, 6, 8]}

        Non-callable keys imply grouping on a member.

        >>> groupby('gender', [{'name': 'Alice', 'gender': 'F'},
        ...                    {'name': 'Bob', 'gender': 'M'},
        ...                    {'name': 'Charlie', 'gender': 'M'}]) # doctest:+SKIP
        {'F': [{'gender': 'F', 'name': 'Alice'}],
         'M': [{'gender': 'M', 'name': 'Bob'},
               {'gender': 'M', 'name': 'Charlie'}]}

        See Also:
            countby

    interleave(seqs, pass_exceptions=())
        Interleave a sequence of sequences

        >>> list(interleave([[1, 2], [3, 4]]))
        [1, 3, 2, 4]

        >>> ''.join(interleave(('ABC', 'XY')))
        'AXBYC'

        Both the individual sequences and the sequence of sequences may be infinite

        Returns a lazy iterator

    interpose(el, seq)
        Introduce element between each pair of elements in seq

        >>> list(interpose("a", [1, 2, 3]))
        [1, 'a', 2, 'a', 3]

    isdistinct(seq)
        All values in sequence are distinct

        >>> isdistinct([1, 2, 3])
        True
        >>> isdistinct([1, 2, 1])
        False

        >>> isdistinct("Hello")
        False
        >>> isdistinct("World")
        True

    isiterable(x)
        Is x iterable?

        >>> isiterable([1, 2, 3])
        True
        >>> isiterable('abc')
        True
        >>> isiterable(5)
        False

    iterate(func, x)
        Repeatedly apply a function func onto an original input

        Yields x, then func(x), then func(func(x)), then func(func(func(x))), etc..

        >>> def inc(x):  return x + 1
        >>> counter = iterate(inc, 0)
        >>> next(counter)
        0
        >>> next(counter)
        1
        >>> next(counter)
        2

        >>> double = lambda x: x * 2
        >>> powers_of_two = iterate(double, 1)
        >>> next(powers_of_two)
        1
        >>> next(powers_of_two)
        2
        >>> next(powers_of_two)
        4
        >>> next(powers_of_two)
        8

    join(leftkey, leftseq, rightkey, rightseq, left_default='__no__default__', right_default='__no__default__')
        Join two sequences on common attributes

        This is a semi-streaming operation.  The LEFT sequence is fully evaluated
        and placed into memory.  The RIGHT sequence is evaluated lazily and so can
        be arbitrarily large.

        >>> friends = [('Alice', 'Edith'),
        ...            ('Alice', 'Zhao'),
        ...            ('Edith', 'Alice'),
        ...            ('Zhao', 'Alice'),
        ...            ('Zhao', 'Edith')]

        >>> cities = [('Alice', 'NYC'),
        ...           ('Alice', 'Chicago'),
        ...           ('Dan', 'Syndey'),
        ...           ('Edith', 'Paris'),
        ...           ('Edith', 'Berlin'),
        ...           ('Zhao', 'Shanghai')]

        >>> # Vacation opportunities
        >>> # In what cities do people have friends?
        >>> result = join(second, friends,
        ...               first, cities)
        >>> for ((a, b), (c, d)) in sorted(unique(result)):
        ...     print((a, d))
        ('Alice', 'Berlin')
        ('Alice', 'Paris')
        ('Alice', 'Shanghai')
        ('Edith', 'Chicago')
        ('Edith', 'NYC')
        ('Zhao', 'Chicago')
        ('Zhao', 'NYC')
        ('Zhao', 'Berlin')
        ('Zhao', 'Paris')

        Specify outer joins with keyword arguments ``left_default`` and/or
        ``right_default``.  Here is a full outer join in which unmatched elements
        are paired with None.

        >>> identity = lambda x: x
        >>> list(join(identity, [1, 2, 3],
        ...           identity, [2, 3, 4],
        ...           left_default=None, right_default=None))
        [(2, 2), (3, 3), (None, 4), (1, None)]

        Usually the key arguments are callables to be applied to the sequences.  If
        the keys are not obviously callable then it is assumed that indexing was
        intended, e.g. the following is a legal change

        >>> # result = join(second, friends, first, cities)
        >>> result = join(1, friends, 0, cities)  # doctest: +SKIP

    last(seq)
        The last element in a sequence

        >>> last('ABC')
        'C'

    mapcat(func, seqs)
        Apply func to each sequence in seqs, concatenating results.

        >>> list(mapcat(lambda s: [c.upper() for c in s],
        ...             [["a", "b"], ["c", "d", "e"]]))
        ['A', 'B', 'C', 'D', 'E']

    merge_sorted(*seqs, **kwargs)
        Merge and sort a collection of sorted collections

        This works lazily and only keeps one value from each iterable in memory.

        >>> list(merge_sorted([1, 3, 5], [2, 4, 6]))
        [1, 2, 3, 4, 5, 6]

        >>> ''.join(merge_sorted('abc', 'abc', 'abc'))
        'aaabbbccc'

        The "key" function used to sort the input may be passed as a keyword.

        >>> list(merge_sorted([2, 3], [1, 3], key=lambda x: x // 3))
        [2, 1, 3, 3]

    nth(n, seq)
        The nth element in a sequence

        >>> nth(1, 'ABC')
        'B'

    partition(n, seq, pad='__no__pad__')
        Partition sequence into tuples of length n

        >>> list(partition(2, [1, 2, 3, 4]))
        [(1, 2), (3, 4)]

        If the length of ``seq`` is not evenly divisible by ``n``, the final tuple
        is dropped if ``pad`` is not specified, or filled to length ``n`` by pad:

        >>> list(partition(2, [1, 2, 3, 4, 5]))
        [(1, 2), (3, 4)]

        >>> list(partition(2, [1, 2, 3, 4, 5], pad=None))
        [(1, 2), (3, 4), (5, None)]

        See Also:
            partition_all

    partition_all(n, seq)
        Partition all elements of sequence into tuples of length at most n

        The final tuple may be shorter to accommodate extra elements.

        >>> list(partition_all(2, [1, 2, 3, 4]))
        [(1, 2), (3, 4)]

        >>> list(partition_all(2, [1, 2, 3, 4, 5]))
        [(1, 2), (3, 4), (5,)]

        See Also:
            partition

    peek(seq)
        Retrieve the next element of a sequence

        Returns the first element and an iterable equivalent to the original
        sequence, still having the element retrieved.

        >>> seq = [0, 1, 2, 3, 4]
        >>> first, seq = peek(seq)
        >>> first
        0
        >>> list(seq)
        [0, 1, 2, 3, 4]

    pluck(ind, seqs, default='__no__default__')
        plucks an element or several elements from each item in a sequence.

        ``pluck`` maps ``itertoolz.get`` over a sequence and returns one or more
        elements of each item in the sequence.

        This is equivalent to running `map(curried.get(ind), seqs)`

        ``ind`` can be either a single string/index or a sequence of
        strings/indices.
        ``seqs`` should be sequence containing sequences or dicts.

        e.g.

        >>> data = [{'id': 1, 'name': 'Cheese'}, {'id': 2, 'name': 'Pies'}]
        >>> list(pluck('name', data))
        ['Cheese', 'Pies']
        >>> list(pluck([0, 1], [[1, 2, 3], [4, 5, 7]]))
        [(1, 2), (4, 5)]

        See Also:
            get
            map

    reduceby(key, binop, seq, init='__no__default__')
        Perform a simultaneous groupby and reduction

        The computation:

        >>> result = reduceby(key, binop, seq, init)      # doctest: +SKIP

        is equivalent to the following:

        >>> def reduction(group):                           # doctest: +SKIP
        ...     return reduce(binop, group, init)           # doctest: +SKIP

        >>> groups = groupby(key, seq)                    # doctest: +SKIP
        >>> result = valmap(reduction, groups)              # doctest: +SKIP

        But the former does not build the intermediate groups, allowing it to
        operate in much less space.  This makes it suitable for larger datasets
        that do not fit comfortably in memory

        The ``init`` keyword argument is the default initialization of the
        reduction.  This can be either a constant value like ``0`` or a callable
        like ``lambda : 0`` as might be used in ``defaultdict``.

        Simple Examples
        ---------------

        >>> from operator import add, mul
        >>> iseven = lambda x: x % 2 == 0

        >>> data = [1, 2, 3, 4, 5]

        >>> reduceby(iseven, add, data)  # doctest: +SKIP
        {False: 9, True: 6}

        >>> reduceby(iseven, mul, data)  # doctest: +SKIP
        {False: 15, True: 8}

        Complex Example
        ---------------

        >>> projects = [{'name': 'build roads', 'state': 'CA', 'cost': 1000000},
        ...             {'name': 'fight crime', 'state': 'IL', 'cost': 100000},
        ...             {'name': 'help farmers', 'state': 'IL', 'cost': 2000000},
        ...             {'name': 'help farmers', 'state': 'CA', 'cost': 200000}]

        >>> reduceby('state',                        # doctest: +SKIP
        ...          lambda acc, x: acc + x['cost'],
        ...          projects, 0)
        {'CA': 1200000, 'IL': 2100000}

        Example Using ``init``
        ----------------------

        >>> def set_add(s, i):
        ...     s.add(i)
        ...     return s

        >>> reduceby(iseven, set_add, [1, 2, 3, 4, 1, 2, 3], set)  # doctest: +SKIP
        {True:  set([2, 4]),
         False: set([1, 3])}

    remove(predicate, seq)
        Return those items of sequence for which predicate(item) is False

        >>> def iseven(x):
        ...     return x % 2 == 0
        >>> list(remove(iseven, [1, 2, 3, 4]))
        [1, 3]

    second(seq)
        The second element in a sequence

        >>> second('ABC')
        'B'

    sliding_window(n, seq)
        A sequence of overlapping subsequences

        >>> list(sliding_window(2, [1, 2, 3, 4]))
        [(1, 2), (2, 3), (3, 4)]

        This function creates a sliding window suitable for transformations like
        sliding means / smoothing

        >>> mean = lambda seq: float(sum(seq)) / len(seq)
        >>> list(map(mean, sliding_window(2, [1, 2, 3, 4])))
        [1.5, 2.5, 3.5]

    tail(n, seq)
        The last n elements of a sequence

        >>> tail(2, [10, 20, 30, 40, 50])
        [40, 50]

        See Also:
            drop
            take

    take(n, seq)
        The first n elements of a sequence

        >>> list(take(2, [10, 20, 30, 40, 50]))
        [10, 20]

        See Also:
            drop
            tail

    take_nth(n, seq)
        Every nth item in seq

        >>> list(take_nth(2, [10, 20, 30, 40, 50]))
        [10, 30, 50]

    topk(k, seq, key=None)
        Find the k largest elements of a sequence

        Operates lazily in ``n*log(k)`` time

        >>> topk(2, [1, 100, 10, 1000])
        (1000, 100)

        Use a key function to change sorted order

        >>> topk(2, ['Alice', 'Bob', 'Charlie', 'Dan'], key=len)
        ('Charlie', 'Alice')

        See also:
            heapq.nlargest

    unique(seq, key=None)
        Return only unique elements of a sequence

        >>> tuple(unique((1, 2, 3)))
        (1, 2, 3)
        >>> tuple(unique((1, 2, 1, 3)))
        (1, 2, 3)

        Uniqueness can be defined by key keyword

        >>> tuple(unique(['cat', 'mouse', 'dog', 'hen'], key=len))
        ('cat', 'mouse')

DATA
    __all__ = ('remove', 'accumulate', 'groupby', 'merge_sorted', 'interle...

FILE
    /Users/pbrown/.virtualenvs/notebooks/lib/python3.4/site-packages/toolz/itertoolz.py